---

- hosts: all

  vars:
    oscap_level: intermediary  # minimal - intermediary - high - enhanced
    oscap_profile: xccdf_org.ssgproject.content_profile_anssi_bp28_{{ oscap_level }}
    oscap_policy: ssg-rhel8-ds

  tasks:

  - block:
    - name: run openscap
      become: true
      command: oscap xccdf eval \
        --profile {{ oscap_profile }} \
        --results-arf /tmp/oscap-arf.xml \
        --report /tmp/oscap-report.html \
        --fetch-remote-resources \
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml

    always:
    - name: download report
      fetch:
        src: /tmp/oscap-report.html
        dest: ../oscap-reports/{{ inventory_hostname }}-{{ oscap_level }}.html
        flat: yes